version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: portafolio
    networks:
      - web-network

networks:
  web-network:
    external: true
