version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network-portfolio

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - network-portfolio

networks:
  network-portfolio:
    driver: bridge
